// <auto-generated />
namespace Hotel.Monitor.DAL.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class removeMaby2Many : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removeMaby2Many));
        
        string IMigrationMetadata.Id
        {
            get { return "201404251009139_removeMaby2Many"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
