// <auto-generated />
namespace Hotel.Monitor.DAL.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class manytomany4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(manytomany4));
        
        string IMigrationMetadata.Id
        {
            get { return "201404250958146_manytomany4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
