// <auto-generated />
namespace Hotel.Monitor.DAL.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class addCheckout : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addCheckout));
        
        string IMigrationMetadata.Id
        {
            get { return "201406081529216_addCheckout"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
