// <auto-generated />
namespace Hotel.Monitor.DAL.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class manytomany : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(manytomany));
        
        string IMigrationMetadata.Id
        {
            get { return "201404250929463_manytomany"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
